devices:
  adci2c:
    1:
      adda: 0x68
      addb: 0x69
      rate: 12
      pins:
        1:
          name: Van Battery 1
          unit: Volts
          factor: 5.1
          offset: 0.1
        2:
          name: Van Battery 2
          unit: Volts
          factor: 5.2
          offset: 0.2
        3:
          name: Van Battery 3
          unit: Volts
          factor: 5.3
          offset: 0.3
    2:
      adda: 0x6a
      addb: 0x6b
      rate: 12
      pins:
        1:
          name: Van Battery 1
          unit: Amps
          factor: 5.0
          offset: 0.0
        2:
          name: Van Battery 2
          unit: Amps
          factor: 5.0
          offset: 0.0
        3:
          name: Van Battery 3
          unit: Amps
          factor: 5.0
          offset: 0.0
