devices:
  adci2c:
    1:
      type: adc
      adda: 0x68
      addb: 0x69
      rate: 12
      pins:
        1:
          name: Van Battery 1
          unit: Volts
          factor: 6.56
          offset: 0.00
        2:
          name: Van Battery 2
          unit: Volts
          factor: 6.60
          offset: 0.00
        3:
          name: Van Battery 3
          unit: Volts
          factor: 6.60
          offset: 0.00
        4:
          name: Van Battery 4
          unit: Volts
          factor: 6.60
          offset: 0.00
        5:
          name: Van Battery 5
          unit: Volts
          factor: 6.60
          offset: 0.00
        6:
          name: Van Battery 6
          unit: Volts
          factor: 6.60
          offset: 0.00
        7:
          name: Van Battery 7
          unit: Volts
          factor: 6.60
          offset: 0.00
        8:
          name: Van Battery 8
          unit: Volts
          factor: 6.60
          offset: 0.00
    2:
      type: adc
      adda: 0x6a
      addb: 0x6b
      rate: 12
      pins:
        1:
          name: Van Battery 1
          unit: Amps
          factor: 6.60
          offset: 0.00
        2:
          name: Van Battery 2
          unit: Amps
          factor: 6.60
          offset: 0.00
        3:
          name: Van Battery 3
          unit: Amps
          factor: 6.60
          offset: 0.00
        4:
          name: Van Battery 4
          unit: Amps
          factor: 6.60
          offset: 0.00
        5:
          name: Van Battery 5
          unit: Amps
          factor: 6.60
          offset: 0.00
        6:
          name: Van Battery 6
          unit: Amps
          factor: 6.60
          offset: 0.00
        7:
          name: Van Battery 7
          unit: Amps
          factor: 6.60
          offset: 0.00
        8:
          name: Van Battery 7
          unit: Amps
          factor: 6.60
          offset: 0.00
  w1:
    1:
      type: therm
      add: 28-000005cf908e
      name: Van Fridge
      unit: Deg C
      factor: 1.0
      offset: 0.00
    2:
      type: therm
      add: 28-000005d01306
      name: Van Internal
      unit: Deg C
      factor: 1.0
      offset: 0.00
