devices:
  adci2c:
    1:
      type: adc
      adda: 0x68
      addb: 0x69
      rate: 12
      pins:
        1:
          name: 1-1
          unit: Volts
          factor: 1.000
          offset: 0.000
        2:
          name: 1-2
          unit: Volts
          factor: 1.000
          offset: 0.000
        3:
          name: 1-3
          unit: Volts
          factor: -6.60
          offset: -4.910
        4:
          name: 1-4
          unit: Volts
          factor: 1.000
          offset: 0.000
        5:
          name: 1-5
          unit: Volts
          factor: 1.000
          offset: 0.000
        6:
          name: 1-6
          unit: Volts
          factor: 1.000
          offset: 0.000
        7:
          name: 1-7
          unit: Volts
          factor: 1.000
          offset: 0.000
        8:
          name: 1-8
          unit: Volts
          factor: 1.000
          offset: 0.000
    2:
      type: adc
      adda: 0x6a
      addb: 0x6b
      rate: 12
      pins:
        1:
          name: 2-1
          unit: Amps
          factor: 6.60
          offset: 0.00
        2:
          name: 2-2
          unit: Amps
          factor: 6.60
          offset: 0.00
        3:
          name: 2-3
          unit: Amps
          factor: 6.60
          offset: 0.00
        4:
          name: 2-4
          unit: Amps
          factor: 6.60
          offset: 0.00
        5:
          name: 2-5
          unit: Amps
          factor: 6.60
          offset: 0.00
        6:
          name: 2-6
          unit: Amps
          factor: 6.60
          offset: 0.00
        7:
          name: 2-7
          unit: Amps
          factor: 6.60
          offset: 0.00
        8:
          name: 2-8
          unit: Amps
          factor: 6.60
          offset: 0.00
  w1:
    1:
      type: therm
      add: 28-000005cf908e
      name: t1
      unit: Deg C
      factor: 1.0
      offset: 0.00
    2:
      type: therm
      add: 28-000005d01306
      name: t2
      unit: Deg C
      factor: 1.0
      offset: 0.00
